name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test application
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: build installDist
      - uses: actions/upload-artifact@v1
        with:
          name: myapplication-${{ github.sha }}
          path: build/install/myapplication

  build_native:
    if: ${{ false }}  # disabled for now
    name: Build and test native application
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: nativeTest
