name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  GRAALVM_VERSION: '22.3.1'
  GRAALVM_COMPONENTS: 'native-image'

permissions:
  contents: read

jobs:
  build:
    name: Build and test application
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: build installDist
      - uses: actions/upload-artifact@v1
        with:
          name: myapplication-${{ github.sha }}
          path: build/install/myapplication

  build_native:
    if: ${{ false }}  # disabled for now
    name: Build and test native application
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          version: ${{ env.GRAALVM_VERSION }}
          components: ${{ env.GRAALVM_COMPONENTS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: nativeTest
