name: Native build with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JAVA_VERSION: '17'
  GRAALVM_VERSION: '22.3.2'
  GRAALVM_COMPONENTS: 'native-image'

permissions:
  contents: read

jobs:
  build_native:
    name: Build and test native application
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ env.GRAALVM_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}
          components: ${{ env.GRAALVM_COMPONENTS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          check-for-updates: 'true'

      - name: Build and Test
        uses: gradle/gradle-build-action@v2.7.0
        with:
          arguments: nativeTest nativeDistZip installNativeDist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gradle_quickstart_native_${{ github.sha }}
          path: build/install/gradle_quickstart-native
